# git-related
BRANCH ?= $(shell git rev-parse --abbrev-ref HEAD | sed -E 's/[_/]+/-/g')
GITIGNORE_RULES ?= python,linux

# Python-related
PYTHON   ?= python3.4
PY_MODULES = mpw
PY_FILES = $(shell find . -type f -name "*.py")

# General rules

all: test

install:
	@ CC=false ${PYTHON} -m pip install \
		--user --upgrade \
		--requirement requirements.txt

pre-commit: autofmt .gitignore test

test:
	@ ${PYTHON} -m pep8 $(PY_FILES)
	@ ${PYTHON} -m nose $(PY_MODULES) $(PY_FILES)

run: test
	@ ${PYTHON} -m mpw

shell:
	@ ${PYTHON} -m IPython

deploy: test
	@ false

autofmt:
	@ ${PYTHON} -m autopep8 -i $(PY_FILES)

clean:
	find . -name "*.pyc" -type f -delete
	find . -name "__pycache__" -type d -delete

.PHONY: all install pre-commit test run shell deploy autofmt clean

.gitignore: .gitignore.local
	@ rm -f .gitignore
	@ echo "# AUTOGENERATED - WILL BE OVERWRITTEN" > .gitignore
	@ echo "# edit .gitignore.local and run make .gitignore" >> .gitignore
	@ echo >> .gitignore
	@ cat .gitignore.local >> .gitignore
	@ echo >> .gitignore
	@ echo '#' https://www.gitignore.io/api/$(GITIGNORE_RULES) >> .gitignore
	@ curl     https://www.gitignore.io/api/$(GITIGNORE_RULES) >> .gitignore

.gitignore.local:
	@touch .gitignore.local
